/**
 * Created by Administrator on 2016/9/20.
 */
var ctrl={
    indexCtrl:['$scope',function($scope){
        var newData=
        { "news":[
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            },
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
            ,
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
            ,
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
            ,
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
            ,
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
            ,
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
            ,
            {
                title:"水彩人像课",
                newName:"MarinaRen",
                newMoney:"￥68.5",
                newLive:"正在预售中…",
                newEnroll:"52人在学"
            }
        ]}
        $scope.name=newData.news;


    }],
    allClass:['$scope',function($scope){
        $scope.name="这是所有课程"
    }],
    myClass:['$scope',function($scope){
        $scope.name="这是我的课程"
    }],
    files:['$scope',function($scope){
        $scope.name="这是文章专栏"
    }],
    appDown:['$scope',function($scope){
        $scope.name="app下载"
    }],
    appLogin:['$scope',function($scope){
        $scope.name="这是登录"
    }]
}